# spring.application.name=lakeside-view-api

# ## Postgres SQL Database config
# spring.datasource.url=jdbc:postgresql://localhost:5432/lakeside_view
# spring.datasource.username=postgres
# spring.datasource.password=nyarragu
# spring.jpa.show-sql=true

spring:
  application:
    name: lakeside-view-api
  datasource:
    ## Postgres Database ##
    # username: postgres
    # password: nyarragu
    # # url: jdbc:postgresql://localhost:5432/lakeside_view
    # url:    dbc:mysql://localhost:3306/lakeside_view
    # driver-class-name: org.postgresql.Driver
    ## MySQL Database ##
    username: root
    password: Nave@0596
    url: jdbc:mysql://localhost:3306/lakeside_view
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect # Postgres Dialect
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database

# Hibernate ddl auto (create, create-drop, validate, update)
# spring.jpa.hibernate.ddl-auto = update

### Postgres SQL Dialect
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
