# spring.application.name=lakeside-view-api
   
# ## Postgres SQL Database config
# spring.datasource.url=jdbc:postgresql://localhost:5432/lakeside_view
# spring.datasource.username=postgres
# spring.datasource.password=nyarragu
# spring.jpa.show-sql=true

spring:
    application:
        name: lakeside-view-api
    datasource:
        username:   postgres
        password:   nyarragu
        url:    jdbc:postgresql://localhost:5432/lakeside_view
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            format_sql: true
        properties:
            hiberbate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
            file-size-threshold: 2KB

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database

# Hibernate ddl auto (create, create-drop, validate, update)
# spring.jpa.hibernate.ddl-auto = update

### Postgres SQL Dialect
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect